/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-19 10:02:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.auth;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>ZUKI</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- title -->\r\n");
      out.write("    <title>ZUKI-Night Restaurant</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- favicon -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/png\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/favicon.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/bootstrap/bootstrap2.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Open+Sans:wght@400;600;700&display=swap');\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: \"Roboto\";\r\n");
      out.write("            src: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/fonts/ROBOTO-LIGHT.TTF\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            background-image: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/zukilogo.svg\");\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-size: contain;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title1 {\r\n");
      out.write("            /*font-family: \"Colonna\";*/\r\n");
      out.write("            font-family: 'Dancing Script', cursive;\r\n");
      out.write("            font-size: 40px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title2 {\r\n");
      out.write("            font-family: \"Roboto\";\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .foot_title {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .background {\r\n");
      out.write("            background-image: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/Food-delivery-logo.png\");\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-size: contain;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-background {\r\n");
      out.write("            background-image: url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/hand-painted-background.jpg\");\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"main-background\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid \">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row align-content-center\">\r\n");
      out.write("\r\n");
      out.write("        <!-- logo and main title -->\r\n");
      out.write("        <div class=\"col-12 mt-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 logo\"></div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <p class=\"text-center title1\">Hi, Welcome to Our Night Restaurant..</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- logo and main title -->\r\n");
      out.write("\r\n");
      out.write("        <!-- image and fields -->\r\n");
      out.write("        <div class=\"col-12 px-5 py-4\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-6 d-none d-lg-block background\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- sign up -->\r\n");
      out.write("                <div class=\"col-12 col-lg-6 d-none\" id=\"signUpBox\">\r\n");
      out.write("                    <div class=\"row g-2\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <p class=\"title2\">Create New Account</p>\r\n");
      out.write("                            <p class=\"text-danger\" id=\"responseMessage\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <label class=\"form-label\">First Name</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" name=\"fname\" id=\"fname\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <label class=\"form-label\">Last Name</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" name=\"lname\" id=\"lname\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-6 \">\r\n");
      out.write("                            <label class=\"form-label\">Email</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" name=\"email_1\" id=\"email_1\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                            <label class=\"form-label\">Password</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"password\" name=\"password_1\" id=\"password_1\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <label class=\"form-label\">Mobile</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" name=\"mobile\" id=\"mobile\" />\r\n");
      out.write("                        </div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <label class=\"form-label\">City</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" name=\"city\" id=\"city\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                            <label class=\"form-label\">Address line 01</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" name=\"line1\" id=\"line1\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                            <label class=\"form-label\">Address line 02</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" name=\"line2\" id=\"line2\" />\r\n");
      out.write("                        </div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-6 d-grid\">\r\n");
      out.write("                            <button class=\"btn btn-primary sign-up\" >Sign Up</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-6 d-grid\">\r\n");
      out.write("                            <button class=\"btn btn-dark\" onclick=\"changeView();\">Already have an account? Sign In </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- sign in -->\r\n");
      out.write("                <div class=\"col-12 col-lg-6 \" id=\"signInBox\">\r\n");
      out.write("                    <div class=\"row g-3\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <p class=\"title2\">Sign In To Your Account</p>\r\n");
      out.write("                            <p class=\"text-danger\" id=\"responseMessage2\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label\">Email</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"text\" name=\"username\" id=\"username\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label\">Password</label>\r\n");
      out.write("                            <input class=\"form-control\" type=\"password\" name=\"password\" id=\"password\"  />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" id=\"remember\" value=\"1\">\r\n");
      out.write("                                <label class=\"form-check-label\">Remember Me</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <a href=\"#\" class=\"link-primary\" >Forgot Password?</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-6 d-grid\">\r\n");
      out.write("                            <button class=\"btn btn-primary btn-sign-in\" >Sign In</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-6 d-grid\">\r\n");
      out.write("                            <button class=\"btn btn-danger\" onclick=\"changeView();\">New to ZUKI? Join Now</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- image and fields -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<div class=\"col-12 d-none d-lg-block\">\r\n");
      out.write("    <p class=\"text-center foot_title\">&copy; 2023 zuki.com All Right Reserved</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- modal -->\r\n");
      out.write("<div class=\"modal fade\" tabindex=\"-1\" id=\"forgetPasswordModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">Password Reset</h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"row g-3\">\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <label class=\"form-label\">New Password</label>\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                            <input class=\"form-control\" type=\"password\" id=\"np\" />\r\n");
      out.write("                            <button class=\"btn btn-outline-primary\" type=\"button\" id=\"npb\" >Show</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-6\">\r\n");
      out.write("                        <label class=\"form-label\">Re-type Password</label>\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                            <input class=\"form-control\" type=\"password\" id=\"rnp\" />\r\n");
      out.write("                            <button class=\"btn btn-outline-primary\" type=\"button\" id=\"rnpb\" >Show</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <label class=\"form-label\">Verification Code</label>\r\n");
      out.write("                        <input class=\"form-control\" type=\"text\" id=\"vc\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" >Reset</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function changeView() {\r\n");
      out.write("        var signInBox = document.getElementById(\"signInBox\");\r\n");
      out.write("        var signUpBox = document.getElementById(\"signUpBox\");\r\n");
      out.write("\r\n");
      out.write("        signInBox.classList.toggle(\"d-none\");\r\n");
      out.write("        signUpBox.classList.toggle(\"d-none\");\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    document.querySelector('.sign-up').addEventListener('click',function(){\r\n");
      out.write("        let email = document.getElementById('email_1').value;\r\n");
      out.write("        let password = document.getElementById('password_1').value;\r\n");
      out.write("        let mobile = document.getElementById('mobile').value;\r\n");
      out.write("        let fname = document.getElementById('fname').value;\r\n");
      out.write("        let lname = document.getElementById('lname').value;\r\n");
      out.write("        let city = document.getElementById('city').value;\r\n");
      out.write("        let line1 = document.getElementById('line1').value;\r\n");
      out.write("        let line2 = document.getElementById('line2').value;\r\n");
      out.write("\r\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("register',{\r\n");
      out.write("            method:'post',\r\n");
      out.write("            headers:{\r\n");
      out.write("                'Content-Type':'application/json'\r\n");
      out.write("            },\r\n");
      out.write("            body:JSON.stringify({\r\n");
      out.write("                email:email,\r\n");
      out.write("                password:password,\r\n");
      out.write("                mobile:mobile,\r\n");
      out.write("                firstname:fname,\r\n");
      out.write("                lastname:lname,\r\n");
      out.write("                city:city,\r\n");
      out.write("                addressline01:line1,\r\n");
      out.write("                addressline02:line2\r\n");
      out.write("            })\r\n");
      out.write("        }).then(async response=>{\r\n");
      out.write("            if(response.ok){\r\n");
      out.write("                alert(\"Register Success & Check Your Email..\");\r\n");
      out.write("                window.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login\"\r\n");
      out.write("            }else{\r\n");
      out.write("                // throw new Error();\r\n");
      out.write("                const errorMessage = await response.text();\r\n");
      out.write("                document.getElementById('responseMessage').innerHTML = errorMessage;\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("            .catch(error=>{\r\n");
      out.write("\r\n");
      out.write("            })\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.querySelector('.btn-sign-in').addEventListener('click',function () {\r\n");
      out.write("        let email = document.querySelector(\"#username\").value;\r\n");
      out.write("        let password = document.querySelector(\"#password\").value;\r\n");
      out.write("\r\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login',{\r\n");
      out.write("            method:'post',\r\n");
      out.write("            headers:{\r\n");
      out.write("                'Content-Type':'application/json'\r\n");
      out.write("            },\r\n");
      out.write("            body:JSON.stringify({\r\n");
      out.write("                email:email,\r\n");
      out.write("                password:password\r\n");
      out.write("            })\r\n");
      out.write("        }).then(async response=>{\r\n");
      out.write("            if(!response.ok){\r\n");
      out.write("                // console.log(response.text());\r\n");
      out.write("                // alert(\"response.text()\");\r\n");
      out.write("                const errorMessage = await response.text();\r\n");
      out.write("                document.getElementById('responseMessage2').innerHTML = errorMessage;\r\n");
      out.write("            }\r\n");
      out.write("            return response.json();\r\n");
      out.write("        }).then(data=>{\r\n");
      out.write("            localStorage.setItem(\"accessToken\",data.accessToken);\r\n");
      out.write("            localStorage.setItem(\"refreshToken\",data.refreshToken);\r\n");
      out.write("            localStorage.setItem(\"expireIn\",data.expireIn);\r\n");
      out.write("\r\n");
      out.write("            //localStorage.setItem(\"token\",JSON.stringify(data));\r\n");
      out.write("            window.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
